#include "core/bootcode/BootCode.h"

#include <cstring>

namespace bootroll {

// bootroll's own NT6-style MBR, assembled from resources/bootcode/nt6_mbr.asm
// at development time (nasm -f bin). Generated by EmbedBinary.cmake.
extern const unsigned char bootcode_nt6_mbr[];
extern const size_t bootcode_nt6_mbr_size;

// Open-source boot code embedded at build time from resources/bootcode/
// (grub4dos 0.4.6a, WEE 63 beta, syslinux 6.03 - see resources/licenses/
// for the corresponding license files and version notes).
extern const unsigned char bootcode_grub4dos_mbr[];   // grldr.mbr, 16 sectors
extern const size_t bootcode_grub4dos_mbr_size;
extern const unsigned char bootcode_grub4dos_pbr[];   // grldr.pbr, 11 sectors
extern const size_t bootcode_grub4dos_pbr_size;
extern const unsigned char bootcode_grub4dos_grldr[]; // GRLDR boot file
extern const size_t bootcode_grub4dos_grldr_size;
extern const unsigned char bootcode_wee63_mbr[];      // wee63.mbr (63-sector track)
extern const size_t bootcode_wee63_mbr_size;
extern const unsigned char bootcode_syslinux_mbr[];   // syslinux mbr.bin, 440 bytes
extern const size_t bootcode_syslinux_mbr_size;

namespace {

bool containsAscii(const uint8_t* p, size_t size, const char* s)
{
    size_t n = std::strlen(s);
    if (size < n)
        return false;
    for (size_t i = 0; i + n <= size; ++i)
        if (std::memcmp(p + i, s, n) == 0)
            return true;
    return false;
}

// WEE installs into a full 63-sector track; the blob itself is 61.7 sectors.
constexpr size_t kWeeTrackSize = 63 * 512;

} // namespace

std::string_view mbrKindLabel(MbrKind k)
{
    switch (k) {
    case MbrKind::Nt6: return "Windows NT 6.x MBR";
    case MbrKind::Nt5: return "Windows NT 5.x MBR";
    case MbrKind::Grub4dos: return "Grub4DOS MBR (grldr)";
    case MbrKind::Wee: return "WEE boot manager MBR";
    case MbrKind::Syslinux: return "Syslinux MBR";
    case MbrKind::Plop: return "Plop Boot Manager MBR";
    case MbrKind::NotMbr: return "No boot signature";
    case MbrKind::Reactive: return "Unknown code (signature only)";
    default: return "Not a boot sector";
    }
}

MbrKind detectMbrKind(const uint8_t* sector, size_t size)
{
    if (size < 512)
        return MbrKind::NotMbr;
    if (sector[0x1FE] != 0x55 || sector[0x1FF] != 0xAA)
        return MbrKind::NotMbr;

    // Code area only (0x1B8 may hold a disk signature, 0x1BE+ the DPT).
    const uint8_t* code = sector;
    const size_t codeSize = 0x1B8;

    // Order matters: the bundled blobs share string fragments with the NT
    // family (syslinux prints "Missing operating system."), so match their
    // unique markers first.
    if (containsAscii(code, codeSize, "Multiple active partitions."))
        return MbrKind::Syslinux;
    if (containsAscii(code, codeSize, "Missing helper.") ||
        containsAscii(code, codeSize, "No GRLDR"))
        return MbrKind::Grub4dos;
    if (containsAscii(code, codeSize, "wee"))
        return MbrKind::Wee;
    if (containsAscii(code, codeSize, "Plop"))
        return MbrKind::Plop;
    if (containsAscii(code, codeSize, "GRUB"))
        return MbrKind::Grub4dos;
    if (containsAscii(code, codeSize, "SYSLINUX"))
        return MbrKind::Syslinux;
    if (containsAscii(code, codeSize, "Missing operating system") ||
        containsAscii(code, codeSize, "Invalid partition table")) {
        // NT family: extended reads (mov ah,41h/42h) mark the NT6 generation.
        for (size_t i = 0; i + 1 < codeSize; ++i) {
            if (code[i] == 0xB4 && (code[i + 1] == 0x41 || code[i + 1] == 0x42))
                return MbrKind::Nt6;
        }
        return MbrKind::Nt5;
    }
    return MbrKind::Reactive;
}

bool mbrInstallInfo(MbrInstallType t, MbrInstallInfo* out)
{
    if (!out)
        return false;
    switch (t) {
    case MbrInstallType::Nt6:
        out->blob = bootcode_nt6_mbr;
        out->blobSize = bootcode_nt6_mbr_size;
        out->multiSector = false;
        return out->blobSize >= 440;
    case MbrInstallType::Grub4dos:
        out->blob = bootcode_grub4dos_mbr;
        out->blobSize = bootcode_grub4dos_mbr_size;
        out->multiSector = true;
        return out->blobSize >= 512;
    case MbrInstallType::Wee:
        out->blob = bootcode_wee63_mbr;
        out->blobSize = bootcode_wee63_mbr_size;
        out->multiSector = true;
        return out->blobSize >= 512;
    case MbrInstallType::Syslinux:
        out->blob = bootcode_syslinux_mbr;
        out->blobSize = bootcode_syslinux_mbr_size;
        out->multiSector = false;
        return out->blobSize >= 440;
    }
    return false;
}

bool stageMbrInstall(MbrInstallType t, const uint8_t* targetSector0, size_t size,
                     std::vector<uint8_t>* staged)
{
    MbrInstallInfo info;
    if (!staged || !targetSector0 || size < 512 || !mbrInstallInfo(t, &info))
        return false;

    if (!info.multiSector) {
        staged->assign(512, 0);
        const size_t codeArea = info.blobSize < 440 ? info.blobSize : 440;
        std::memcpy(staged->data(), info.blob, codeArea);
        // Preserve the target's disk signature, partition table and signature.
        std::memcpy(staged->data() + 440, targetSector0 + 440, 512 - 440);
        return true;
    }

    staged->assign(info.blob, info.blob + info.blobSize);
    if (t == MbrInstallType::Wee) {
        staged->resize(kWeeTrackSize, 0); // zero-pad to a full track
    }
    // Sector 0 keeps the target's disk signature + partition table area.
    std::memcpy(staged->data() + 0x1B8, targetSector0 + 0x1B8, 0x1FE - 0x1B8);
    return true;
}

bool applyMbrCode(uint8_t* sector, size_t size, MbrInstallType t)
{
    MbrInstallInfo info;
    if (!sector || size < 512 || !mbrInstallInfo(t, &info) || info.multiSector)
        return false;
    std::memcpy(sector, info.blob, 440); // bytes [440,512) stay untouched
    return true;
}

const uint8_t* grub4dosGrldrBlob(size_t* size)
{
    if (size)
        *size = bootcode_grub4dos_grldr_size;
    return bootcode_grub4dos_grldr;
}

const uint8_t* grub4dosPbrBlob(size_t* size)
{
    if (size)
        *size = bootcode_grub4dos_pbr_size;
    return bootcode_grub4dos_pbr;
}

const uint8_t* wee63MbrBlob(size_t* size)
{
    if (size)
        *size = bootcode_wee63_mbr_size;
    return bootcode_wee63_mbr;
}

} // namespace bootroll
