# Spec for container-local rpmbuild (M10). Library dependencies are resolved
# automatically by rpm's find-requires from the linked binary; only weak deps
# are declared manually. Package names for weak deps are NOT yet verified on
# all targets (M9 left-over) - unknown names only produce warnings.
Name:           bootroll
Version:        0.2.0
Release:        1%{?dist}
Summary:        Boot manager utility (BOOTICEx64 clean-room rewrite)
License:        GPL-2.0 AND MIT AND GPL-3.0-or-later
URL:            https://localhost/bootroll
Source0:        bootroll-%{version}.tar.gz

ExclusiveArch:  x86_64
BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  glfw-devel
%if 0%{?suse_version}
BuildRequires:  Mesa-libGL-devel
%else
BuildRequires:  mesa-libGL-devel
%endif
# Library deps (libglfw.so.3 etc.) are generated by find-requires from the
# linked binary - do NOT add distro-specific package names here.
Recommends:     zenity
Suggests:       polkit
# CJK font package names differ per distro family and are not yet verified
# (see docs/DISTRO_NOTES.md §2); the app falls back to its embedded font.

%description
Boot sector (MBR/PBR), BCD and UEFI boot entry management with a hex-based
sector editor and bootcode installers.
License mix: GPL-2.0 (bundled GRUB4DOS bootcode), MIT (imgui), GPL
(tinygettext), project code (see LEGAL.md).

%prep
%setup -q

%build
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build %{?_smp_mflags}

%install
DESTDIR=%{buildroot} cmake --install build --prefix /usr
# Prune foreign install rules (tinygettext ships its own install()).
rm -rf %{buildroot}/usr/lib %{buildroot}/usr/lib64 %{buildroot}/usr/include

%files
%license LEGAL.md
/usr/bin/bootroll
/usr/share/applications/bootroll.desktop
/usr/share/icons/hicolor/128x128/apps/bootroll.png

%changelog
* Tue Oct 06 2026 bootroll-dev <bootroll-dev@localhost> - 0.2.0-1
- First packaging milestone (M10).
