#include "app/App.h"
#include "app/I18n.h"
#include "core/util/LocalTime.h"
#include "app/Settings.h"
#include "imgui.h"
#include "ui/AboutScreen.h"
#include "ui/BcdEditorScreen.h"
#include "ui/Grub4dosScreen.h"
#include "ui/MainScreen.h"
#include "ui/MbrScreen.h"
#include "ui/PartitionScreen.h"
#include "ui/PbrScreen.h"
#include "ui/SectorScreen.h"
#include "ui/UefiScreen.h"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <ctime>
#include <fstream>
#include <mutex>
#include <thread>

#include "Version.h" // BOOTROLL_GIT_HASH (CMake-generated)

#ifdef _WIN32
#include <windows.h>
#endif

namespace bootroll {

// Embedded fallback font (generated by cmake/EmbedBinary.cmake).
extern const unsigned char font_noto_sc[];
extern const size_t font_noto_sc_size;

// A per-disk probe stuck longer than this logs a warning; warned-but-unfinished
// probes count as stalled in the summary line.
constexpr double kStallWarnSecs = 10.0;

bool App::init(IPlatform* platform, const char* version)
{
    m_platform = platform;
    m_version = version;

    Settings::instance().load(m_platform->iniPath());
    I18n::instance().init();
    I18n::instance().setLanguage(Settings::instance().language);

    log("---- boot " + m_version + " (commit " + BOOTROLL_GIT_HASH + ") ----");
    log("elevated: " + std::string(platform->isElevated() ? "yes" : "no"));
    switch (platform->firmwareType()) {
    case FirmwareType::Bios: log("firmware: BIOS"); break;
    case FirmwareType::Uefi: log("firmware: UEFI"); break;
    default: log("firmware: unknown"); break;
    }
    log("language: " + I18n::instance().language());
    // i18n diagnostics: prove catalogs loaded and translation works.
    std::string catalogs;
    for (const std::string& l : I18n::instance().availableLanguages()) {
        catalogs += (catalogs.empty() ? "" : ",") + l;
    }
    log("i18n catalogs: [" + catalogs + "]");
    log("i18n sample: 'BCD Edit' -> " + I18n::instance().translate("BCD Edit"));

    m_dpiScale = m_platform->dpiScale();
    log("dpi scale: " + std::to_string(m_dpiScale));

    applyTheme(m_dpiScale);
    loadFonts(m_dpiScale);

    m_diskAccess = platform->createDiskAccess();
    refreshDisks();
    return true;
}

void App::shutdown()
{
    Settings::instance().language = I18n::instance().language();
    if (m_lastWidth > 0) {
        Settings::instance().windowWidth = m_lastWidth;
    }
    if (m_lastHeight > 0) {
        Settings::instance().windowHeight = m_lastHeight;
    }
    Settings::instance().save(m_platform->iniPath());
    log("exit");
}

void App::log(const std::string& line, LogLevel level)
{
    char stamp[40];
    const std::time_t now = std::time(nullptr);
    const std::tm tm = localTm(now);
    std::strftime(stamp, sizeof stamp, "%Y-%m-%d %H:%M:%S", &tm);
    const char* tag = "II";
    if (level == LogLevel::Warn) {
        tag = "WW";
    } else if (level == LogLevel::Error) {
        tag = "EE";
    }
    std::ofstream out(m_platform->logPath(), std::ios::app | std::ios::binary);
    if (out) {
        out << stamp << " [" << tag << "] " << line << "\n";
    }
}

void App::applyTheme(float scale)
{
    ImGui::StyleColorsDark();
    ImGuiStyle& s = ImGui::GetStyle();
    s.WindowRounding = 4.0f;
    s.FrameRounding = 3.0f;
    s.GrabRounding = 3.0f;
    s.TabRounding = 4.0f;
    s.FramePadding = ImVec2(8, 4);
    s.ItemSpacing = ImVec2(8, 6);
    s.WindowPadding = ImVec2(10, 10);

    ImVec4* c = s.Colors;
    c[ImGuiCol_WindowBg] = ImVec4(0.08f, 0.09f, 0.10f, 1.0f);
    c[ImGuiCol_TitleBgActive] = ImVec4(0.13f, 0.15f, 0.18f, 1.0f);
    c[ImGuiCol_Header] = ImVec4(0.22f, 0.34f, 0.52f, 1.0f);
    c[ImGuiCol_HeaderHovered] = ImVec4(0.26f, 0.40f, 0.60f, 1.0f);
    c[ImGuiCol_Button] = ImVec4(0.18f, 0.22f, 0.29f, 1.0f);
    c[ImGuiCol_ButtonHovered] = ImVec4(0.24f, 0.32f, 0.44f, 1.0f);
    c[ImGuiCol_ButtonActive] = ImVec4(0.28f, 0.40f, 0.58f, 1.0f);
    c[ImGuiCol_FrameBg] = ImVec4(0.14f, 0.16f, 0.19f, 1.0f);

    // Scale every padding/spacing/rounding value set above for the display DPI.
    s.ScaleAllSizes(scale);
}

void App::loadFonts(float scale)
{
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->Clear(); // safe on first call; required on DPI-change reloads
    const float size = 16.0f * scale;
    const ImWchar* ranges = io.Fonts->GetGlyphRangesChineseSimplifiedCommon();

    for (const std::string& path : m_platform->candidateFontPaths()) {
        ImFont* f = io.Fonts->AddFontFromFileTTF(path.c_str(), size, nullptr, ranges);
        if (f) {
            m_fontUsed = path;
            break;
        }
    }
    if (ImGui::GetIO().Fonts->Fonts.empty()) {
        ImFontConfig cfg;
        cfg.FontDataOwnedByAtlas = false;
        ImGui::GetIO().Fonts->AddFontFromMemoryTTF(
            const_cast<unsigned char*>(font_noto_sc),
            (int)font_noto_sc_size, size, &cfg, ranges);
        m_fontUsed = "<embedded NotoSansSC subset>";
    }
    // Fixed-pitch font for hex grids (sector editor); falls back to the
    // first loaded font when Consolas is unavailable.
#ifdef _WIN32
    char winDir[MAX_PATH];
    const UINT n = GetWindowsDirectoryA(winDir, MAX_PATH);
    if (n > 0 && n < MAX_PATH) {
        const std::string mono = std::string(winDir, n) + "\\Fonts\\consola.ttf";
        m_hexFont = io.Fonts->AddFontFromFileTTF(mono.c_str(), size, nullptr,
                                                 io.Fonts->GetGlyphRangesDefault());
    }
#endif
    if (!m_hexFont && !io.Fonts->Fonts.empty()) {
        m_hexFont = io.Fonts->Fonts[0];
    }
    log("font: " + m_fontUsed);
}

void App::setDpiScale(float scale)
{
    if (scale == m_dpiScale) {
        return;
    }
    m_dpiScale = scale;
    applyTheme(scale);
    loadFonts(scale);
    log("dpi scale changed: " + std::to_string(scale));
}

void App::onResize(int width, int height)
{
    m_lastWidth = width;
    m_lastHeight = height;
}

void App::refreshDisks()
{
    auto state = m_diskEnum;
    uint64_t generation = 0;
    {
        std::lock_guard<std::mutex> lk(state->mutex);
        if (state->running) {
            return; // enumeration already in flight
        }
        state->running = true;
        state->completed.clear();
        state->error.clear();
        state->probes.clear();
        state->discoveryDone = false;
        state->discoveryWarned = false;
        state->startedAt = std::chrono::steady_clock::now();
        generation = ++state->generation;
    }
    log("disk enumeration started");
    // Workers own shared_ptr copies of the state and the disk access, so a
    // stalled probe survives App shutdown without use-after-free.
    auto access = m_diskAccess;
    std::thread([state, access, generation]() {
        std::vector<DiskInfo> stubs;
        std::string error;
        try {
            stubs = access->discoverDisks();
        } catch (const std::exception& e) {
            error = e.what();
        }

        std::vector<DiskEnumState::ProbeResult> stubResults;
        {
            std::lock_guard<std::mutex> lk(state->mutex);
            if (state->generation != generation) {
                return; // superseded by a newer refresh
            }
            state->error = std::move(error);
            state->discoveryDone = true;
            for (auto& s : stubs) {
                state->probes.push_back({s.number, std::chrono::steady_clock::now(), false, false});
                DiskEnumState::ProbeResult r;
                r.disk = std::move(s);
                r.stub = true;
                r.first = stubResults.empty();
                stubResults.push_back(std::move(r));
            }
            // Stubs make every disk show up immediately; the per-disk results
            // below replace them in place as they arrive.
            for (const auto& r : stubResults) {
                state->completed.push_back(r);
            }
        }

        // One thread per disk: a device stuck in kernel I/O delays only its
        // own probe; the other disks keep reporting.
        for (const auto& r : stubResults) {
            std::thread([state, access, generation, disk = r.disk]() mutable {
                const auto started = std::chrono::steady_clock::now();
                std::string error;
                try {
                    access->fillDiskDetails(disk);
                } catch (const std::exception& e) {
                    error = e.what();
                }
                DiskEnumState::ProbeResult out;
                out.disk = std::move(disk);
                out.error = std::move(error);
                out.elapsedMs = std::chrono::duration<double, std::milli>(
                                    std::chrono::steady_clock::now() - started)
                                    .count();
                std::lock_guard<std::mutex> lk(state->mutex);
                if (state->generation != generation) {
                    return; // stale probe from a superseded refresh
                }
                for (auto& p : state->probes) {
                    if (p.number == out.disk.number) {
                        p.finished = true;
                    }
                }
                state->completed.push_back(std::move(out));
            }).detach();
        }
    }).detach();
}

void App::pumpDiskEnum()
{
    auto state = m_diskEnum;
    std::vector<DiskEnumState::ProbeResult> harvested;
    std::vector<uint32_t> stalledNumbers;
    std::string discoveryError;
    bool discoveryStalled = false;
    bool settled = false;
    size_t total = 0;
    size_t stalled = 0;
    double totalMs = 0.0;
    {
        std::lock_guard<std::mutex> lk(state->mutex);
        if (!state->running && state->completed.empty() && state->error.empty()) {
            return; // idle
        }
        harvested = std::move(state->completed);
        state->completed.clear();
        discoveryError = std::move(state->error);
        state->error.clear();

        if (state->running) {
            const auto now = std::chrono::steady_clock::now();
            totalMs = std::chrono::duration<double, std::milli>(now - state->startedAt).count();
            if (state->discoveryDone) {
                for (auto& p : state->probes) {
                    if (p.finished) {
                        continue;
                    }
                    const double secs = std::chrono::duration<double>(now - p.started).count();
                    if (!p.warned && secs >= kStallWarnSecs) {
                        p.warned = true;
                        stalledNumbers.push_back(p.number);
                    }
                }
                for (const auto& p : state->probes) {
                    if (p.warned && !p.finished) {
                        ++stalled;
                    }
                }
                total = state->probes.size();
                settled = std::all_of(state->probes.begin(), state->probes.end(),
                                      [](const DiskEnumState::Probe& p) {
                                          return p.finished || p.warned;
                                      });
            } else if (!state->discoveryWarned) {
                const double secs = std::chrono::duration<double>(now - state->startedAt).count();
                if (secs >= kStallWarnSecs) {
                    state->discoveryWarned = true;
                    discoveryStalled = true;
                }
            }
        }
    }

    if (!discoveryError.empty()) {
        log("disk discovery failed: " + discoveryError, LogLevel::Error);
    }
    if (discoveryStalled) {
        log("disk discovery still running (>10 s)", LogLevel::Warn);
    }
    for (uint32_t n : stalledNumbers) {
        log("disk " + std::to_string(n) + ": probe stalled (>10 s)", LogLevel::Warn);
    }

    // Results arrive one by one. The first stub of a refresh replaces the
    // whole list (disks may have been plugged/unplugged); every later result
    // replaces its entry in place so combo indices stay stable.
    for (auto& r : harvested) {
        if (r.first) {
            m_diskList.clear();
            m_selectedDisk = -1;
        }
        // Capture log fields before the disk is moved into the list.
        const bool isDetail = !r.stub;
        const uint32_t number = r.disk.number;
        const std::string name = r.disk.model.empty() ? "(unknown model)" : r.disk.model;
        const size_t partCount = r.disk.partitions.size();

        bool replaced = false;
        for (auto& d : m_diskList) {
            if (d.number == r.disk.number) {
                d = std::move(r.disk);
                replaced = true;
                break;
            }
        }
        if (!replaced) {
            m_diskList.push_back(std::move(r.disk));
        }
        if (isDetail) {
            char ms[32];
            std::snprintf(ms, sizeof ms, "%.0f", r.elapsedMs);
            if (r.error.empty()) {
                log("disk " + std::to_string(number) + ": " + name + ", " +
                    std::to_string(partCount) + " partitions, " + ms + " ms");
            } else {
                log("disk " + std::to_string(number) + ": probe failed after " +
                        ms + " ms: " + r.error,
                    LogLevel::Warn);
            }
        }
    }
    if (!harvested.empty()) {
        // Keep the selection pointing at the same disk across inserts/sorts.
        const bool hadSelection =
            m_selectedDisk >= 0 && m_selectedDisk < (int)m_diskList.size();
        const uint32_t selectedNumber =
            hadSelection ? m_diskList[m_selectedDisk].number : 0;
        std::sort(m_diskList.begin(), m_diskList.end(),
                  [](const DiskInfo& a, const DiskInfo& b) { return a.number < b.number; });
        m_selectedDisk = -1;
        if (hadSelection) {
            for (int i = 0; i < (int)m_diskList.size(); ++i) {
                if (m_diskList[i].number == selectedNumber) {
                    m_selectedDisk = i;
                    break;
                }
            }
        } else if (!m_diskList.empty()) {
            m_selectedDisk = 0; // prefer the system disk (lowest number)
        }
    }

    if (settled) {
        char ms[32];
        std::snprintf(ms, sizeof ms, "%.0f", totalMs);
        log("disks enumerated: " + std::to_string(total) + " in " + ms + " ms (" +
            std::to_string(stalled) + " stalled)");
        std::lock_guard<std::mutex> lk(state->mutex);
        state->running = false;
    }
}

void App::selectDisk(int index)
{
    if (index >= 0 && index < (int)m_diskList.size()) {
        m_selectedDisk = index;
    }
}

const DiskInfo* App::currentDisk() const
{
    if (m_selectedDisk >= 0 && m_selectedDisk < (int)m_diskList.size()) {
        return &m_diskList[m_selectedDisk];
    }
    return nullptr;
}

void App::drawTopBar()
{
    MainScreen::drawTopBar(*this);
}

void App::drawPlaceholder(Page, const char* title, const char* milestone)
{
    ImGui::TextUnformatted(title);
    ImGui::Separator();
    ImGui::TextWrapped("%s", T_("This feature is not implemented yet."));
    ImGui::TextWrapped("%s", milestone);
}

void App::drawPage()
{
    switch (m_page) {
    case Page::Main:
        MainScreen::drawBody(*this);
        break;
    case Page::Bcd:
        BcdEditorScreen::drawBody(*this);
        break;
    case Page::Mbr:
        MbrScreen::drawBody(*this);
        break;
    case Page::Pbr:
        PbrScreen::drawBody(*this);
        break;
    case Page::Grub4dos:
        Grub4dosScreen::drawBody(*this);
        break;
    case Page::Partition:
        PartitionScreen::drawBody(*this);
        break;
    case Page::Sector:
        SectorScreen::drawBody(*this);
        break;
    case Page::Uefi:
        UefiScreen::drawBody(*this);
        break;
    case Page::About:
        AboutScreen::draw(*this);
        break;
    }
}

void App::drawFrame()
{
    // Pick up background disk enumeration results before any screen reads them.
    pumpDiskEnum();

    // Full-viewport host window. Without it ImGui dumps bare widgets into its
    // auto-created "Debug" fallback window (a title bar inside our OS window).
    const ImGuiViewport* vp = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(vp->WorkPos);
    ImGui::SetNextWindowSize(vp->WorkSize);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
    ImGui::Begin("##main", nullptr,
                 ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse |
                     ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove |
                     ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus |
                     ImGuiWindowFlags_NoSavedSettings);
    ImGui::PopStyleVar(2);

    drawTopBar();
    ImGui::Separator();
    MainScreen::drawTabBar(*this);
    drawPage();

    ImGui::End();

    if (m_showDemo) {
        ImGui::ShowDemoWindow(&m_showDemo);
    }
}

} // namespace bootroll
