#include "app/I18n.h"
#include "platform/IPlatform.h"

#include <map>
#include <memory>
#include <sstream>

#include <tinygettext/file_system.hpp>

namespace bootroll {

// Embedded .po catalogs (generated by cmake/EmbedBinary.cmake, external linkage).
extern const unsigned char po_zh_cn[];
extern const size_t po_zh_cn_size;
extern const unsigned char po_en_us[];
extern const size_t po_en_us_size;

namespace {

struct EmbeddedCatalog {
    const unsigned char* data;
    size_t size;
    const char* name;
};

const EmbeddedCatalog kCatalogs[] = {
    { po_zh_cn, po_zh_cn_size, "zh_CN.po" },
    { po_en_us, po_en_us_size, "en_US.po" },
};

// tinygettext::FileSystem serving the embedded catalogs from memory.
class EmbeddedFileSystem : public tinygettext::FileSystem {
public:
    std::vector<std::string> open_directory(const std::string&) override
    {
        std::vector<std::string> names;
        for (const auto& c : kCatalogs) {
            names.push_back(c.name);
        }
        return names;
    }

    std::unique_ptr<std::istream> open_file(const std::string& filename) override
    {
        // tinygettext requests "<search-path>/<name>"; match on the basename.
        std::string base = filename.substr(filename.find_last_of('/') + 1);
        for (const auto& c : kCatalogs) {
            if (base == c.name) {
                std::string bytes(reinterpret_cast<const char*>(c.data), c.size);
                return std::make_unique<std::istringstream>(std::move(bytes));
            }
        }
        return nullptr;
    }
};

} // namespace

I18n::I18n()
    : m_mgr(std::make_unique<EmbeddedFileSystem>())
{
}

I18n& I18n::instance()
{
    static I18n inst;
    return inst;
}

void I18n::init()
{
    // Without a search path, get_dictionary()'s scan loop never runs and every
    // translate() falls back to msgid. The path itself is meaningless for the
    // embedded filesystem (we match on basename), it just must be non-empty.
    m_mgr.add_directory("/");
}

void I18n::setLanguage(const std::string& lang)
{
    m_language = lang;
    if (lang.empty()) {
        m_mgr.set_language(tinygettext::Language());
    } else {
        m_mgr.set_language(tinygettext::Language::from_env(lang));
    }
}

std::vector<std::string> I18n::availableLanguages() const
{
    std::vector<std::string> out;
    for (const auto& lang : const_cast<tinygettext::DictionaryManager&>(m_mgr).get_languages()) {
        out.push_back(lang.str());
    }
    return out;
}

std::string I18n::translate(const std::string& msgid) const
{
    // get_dictionary() is not const in tinygettext; the returned Dictionary::translate is.
    return const_cast<tinygettext::DictionaryManager&>(m_mgr).get_dictionary().translate(msgid);
}

} // namespace bootroll
