# Embed a binary file as a C byte array compiled into the target.
# Usage:
#   include(cmake/EmbedBinary.cmake)
#   embed_binary(<symbol> <input_file> <out_cpp_var>)
# Generates ${CMAKE_BINARY_DIR}/generated/${symbol}.cpp defining:
#   namespace bootroll { const unsigned char <symbol>[]; const size_t <symbol>_size; }
function(embed_binary symbol input_file out_cpp_var)
    set(_out_dir "${CMAKE_BINARY_DIR}/generated")
    set(_out_cpp "${_out_dir}/${symbol}.cpp")
    file(MAKE_DIRECTORY "${_out_dir}")

    file(READ "${input_file}" _hex HEX)
    # group into 0xXX, entries
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE ",$" "" _bytes "${_bytes}")
    string(LENGTH "${_hex}" _nibbles)
    math(EXPR _size "${_nibbles} / 2")

    file(GENERATE OUTPUT "${_out_cpp}" CONTENT
"// Auto-generated by EmbedBinary.cmake from ${input_file}. Do not edit.
#include <cstddef>
namespace bootroll {
extern const unsigned char ${symbol}[] = {
${_bytes}
};
extern const size_t ${symbol}_size = ${_size};
}
")
    set(${out_cpp_var} "${_out_cpp}" PARENT_SCOPE)
    set_source_files_properties("${_out_cpp}" PROPERTIES GENERATED TRUE)
endfunction()
